### PR TITLE
Merging new direction of rotation and joint limits

### PR DESCRIPTION
**Pull request by rsantos88**
Merging new direction of rotation and joint limits

### CODE REVIEW

**Comment by jgvictores** [comment]
@rsantos88 WIP or ready to merge?

**Comment by rsantos88** [comment]
Yes, WIP but soon ready to merge

**Comment by rsantos88** [comment]
Now it's ready to merge

**Comment by rsantos88** [comment]
Sorry, not ready yet, I need to modify the sign of `trs`

**Comment by rsantos88** [comment]
This pull request is ready to merge. Review it if something has escaped me

**Pull request merged**
